/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collector.gui;

import collector.dao.ComplaintDAO;
import collector.pojo.AuthorityCredential;
import collector.pojo.Complaint;
import collector.pojo.OperatorCredential;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import javax.mail.PasswordAuthentication;
import java.sql.SQLException;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahul
 */

public class UserEndComplaintWindow extends javax.swing.JFrame {
     String name,aadhar,subject,matter,address,email,phone;
     String name1,sub1,matter1;
     File document;
     AuthorityCredential authority;
     OperatorCredential operator;
    /**
     * Creates new form UserEnd
     */
    public UserEndComplaintWindow() {
        initComponents();
        super.setLocationRelativeTo(null);
        setTitle("JanSeva  UserEnd Complaint Window");
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/images/man.png"));
        setIconImage(icon1.getImage());
            super.setResizable(false);setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
	setVisible(true);
    }
    public UserEndComplaintWindow(OperatorCredential operator,AuthorityCredential authority) {
        this();
        this.operator = operator;
        this.authority = authority;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLablename = new javax.swing.JLabel();
        jLableaadhar = new javax.swing.JLabel();
        jLablematter = new javax.swing.JLabel();
        jLablesubject = new javax.swing.JLabel();
        jLablephone = new javax.swing.JLabel();
        jLableaddress = new javax.swing.JLabel();
        jLablemail = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jtxtAadhar = new javax.swing.JTextField();
        jtxtAdd = new javax.swing.JTextField();
        jtxtSubject = new javax.swing.JTextField();
        jtxtPhn = new javax.swing.JTextField();
        jtxtMail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaMatter = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnAttatchment = new javax.swing.JButton();
        lblLogout = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("JAN SEVA ");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLablename.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLablename.setText("Name");

        jLableaadhar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLableaadhar.setText("Aadhar");

        jLablematter.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLablematter.setText("Matter");

        jLablesubject.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLablesubject.setText("Subject");

        jLablephone.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLablephone.setText("Phone");

        jLableaddress.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLableaddress.setText("Address");

        jLablemail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLablemail.setText("Email");

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jtxtAreaMatter.setColumns(20);
        jtxtAreaMatter.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaMatter);

        btnSend.setBackground(new java.awt.Color(255, 255, 255));
        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_Sed-09_2236081 (4).png"))); // NOI18N
        btnSend.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSend.setOpaque(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Complaint Window");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("© JanSeva");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Jan Seva");

        BtnAttatchment.setBackground(new java.awt.Color(255, 255, 255));
        BtnAttatchment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filebrowser.png"))); // NOI18N
        BtnAttatchment.setText("browse");
        BtnAttatchment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAttatchmentActionPerformed(evt);
            }
        });

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout1.png"))); // NOI18N
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLableaddress)
                                    .addComponent(jLablemail)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLablematter, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLablesubject, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLableaadhar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLablename, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnAttatchment)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLablephone)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jtxtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtAadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 254, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(222, 222, 222)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSend)
                                        .addGap(511, 511, 511)))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLablename))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLableaadhar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLablesubject))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLablematter))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLableaddress))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLablephone)
                    .addComponent(jtxtPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLablemail))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAttatchment, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        User u=new User(jtxtName.getText(),jtxtAadhar.getText(),jtxtSubject.getText(),jtxtAreaMatter.getText(),jtxtAdd.getText(),jtxtMail.getText(),jtxtPhn.getText());
        try {
            name1=jtxtName.getText();
            sub1=jtxtSubject.getText();
            matter1=jtxtAreaMatter.getText();
            int cId=ComplaintDAO.getNextID();
            System.out.println(cId+"~"+jtxtSubject.getText());
           
            if(document == null) {
                JOptionPane.showMessageDialog(null, "Please Attatch a valid document to support your complaint", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Mailer.send(authority.getConfidentialEmail(),authority.getPassword(),"officeofcollector@gmail.com", cId+"~"+jtxtSubject.getText(), u.toString(),document);
//            System.out.println(u.toString());
            Complaint complaint = new Complaint(cId,sub1,matter1,Long.parseLong(jtxtAadhar.getText()),new Date(),document.getAbsolutePath(),null);
            ComplaintDAO.registerComplaint(complaint);
            JOptionPane.showMessageDialog(null, "Message Sent Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            jtxtName.setText("");
            jtxtSubject.setText("");
            jtxtAadhar.setText("");
            jtxtAdd.setText("");
            jtxtMail.setText("");
            jtxtPhn.setText("");
            jtxtAreaMatter.setText("");
            System.out.println(name1+"  "+sub1+"  "+matter1);
            PrintReportUserEnd user = new PrintReportUserEnd(name1,String.valueOf(cId),sub1,matter1,authority,operator);
            user.setVisible(rootPaneCheckingEnabled);
//            this.dispose();
        } 
        catch (SQLException ex) {
            ex.printStackTrace();
        }

        
    }//GEN-LAST:event_btnSendActionPerformed

    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void BtnAttatchmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAttatchmentActionPerformed
       JOptionPane.showMessageDialog(null, "Please choose .PNG Image with size <200kb", "Info", JOptionPane.INFORMATION_MESSAGE);
        JFileChooser jFileChooser = new JFileChooser();
	jFileChooser.setCurrentDirectory(new File("."));
	int result = jFileChooser.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
		document = jFileChooser.getSelectedFile();
            }
    
    }//GEN-LAST:event_BtnAttatchmentActionPerformed

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.dispose();
        UserEndWelcome login = new UserEndWelcome();
                login.setVisible(true);
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(Color.red);
        Font f = new Font("Tahoma", Font.BOLD, 11);
        lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setForeground(new Color(0, 0, 0));
        Font f = new Font("Tahoma", Font.PLAIN, 11);
        lblLogout.setFont(f);
    }//GEN-LAST:event_lblLogoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            java.util.logging.Logger.getLogger(UserEndComplaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserEndComplaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserEndComplaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserEndComplaintWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserEndComplaintWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAttatchment;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLableaadhar;
    private javax.swing.JLabel jLableaddress;
    private javax.swing.JLabel jLablemail;
    private javax.swing.JLabel jLablematter;
    private javax.swing.JLabel jLablename;
    private javax.swing.JLabel jLablephone;
    private javax.swing.JLabel jLablesubject;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtxtAadhar;
    private javax.swing.JTextField jtxtAdd;
    private javax.swing.JTextArea jtxtAreaMatter;
    private javax.swing.JTextField jtxtMail;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhn;
    private javax.swing.JTextField jtxtSubject;
    private javax.swing.JLabel lblLogout;
    // End of variables declaration//GEN-END:variables

}
class Mailer {
    public static void send(String from, String password, String to, String sub, String msg, File document) {
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");
        //get Session   
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(from, password);
            }
        });
        try {
            MimeMessage message = new MimeMessage(session);
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            message.setSubject(sub);
            MimeBodyPart bodyPart = new MimeBodyPart();
            bodyPart.setText(msg);
            if(document != null) {
                String filename = document.getAbsolutePath();
                Multipart multipart = new MimeMultipart();
                MimeBodyPart attachment = new MimeBodyPart();
                attachment.attachFile(filename);
                multipart.addBodyPart(attachment);
                multipart.addBodyPart(bodyPart);
                message.setContent(multipart);
            }
            Transport.send(message);
            System.out.println("message sent successfully");
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        } catch (IOException ex) {
            Logger.getLogger(Mailer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
class User{
    String name,aadhar,subject,matter,address,email,phone;
    
    @Override
    public String toString() {
        return   name + "~" + aadhar +"~" + matter + "~" + address + "~" + email + "~" + phone;
    }

    public User(String name, String aadhar, String subject, String matter, String address, String email, String phone) {
        this.name = name;
        this.aadhar = aadhar;
        this.subject = subject;
        this.matter = matter;
        this.address = address;
        this.email = email;
        this.phone = phone;
    }
}
